# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

[[ "$(whoami)" = "root" ]] && return

[[ -z "$FUNCNEST" ]] && export FUNCNEST=100 # limits recursive functions, see 'man bash'

## Use the up and down arrow keys for finding a command in history
## (you can write some initial letters of the command first).
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

#export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gcr/ssh"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/alex/.sdkman"
[[ -s "/home/alex/.sdkman/bin/sdkman-init.sh" ]] && source "/home/alex/.sdkman/bin/sdkman-init.sh"
