export EDITOR=nano
export BROWSER=chrome

ZSH_THEME="robbyrussell"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=250'

dotfiles() { ~/.dotfiles/arch.sh; }

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Docker
# Stop all containers
dks() { docker kill $(docker ps -q) "$@"; }
# Delete all containers
dkrm() { docker rm $(docker ps -a -q) "$@"; }
# Delete all images
dkrmi() { docker rmi $(docker images -q) "$@"; }

source /home/linuxbrew/.linuxbrew/opt/antidote/share/antidote/antidote.zsh

antidote load

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

alias tg="terragrunt"

eval "$(mise activate zsh)"

export SDKMAN_DIR=$(brew --prefix sdkman-cli)/libexec
[[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"

RPROMPT='$(kube_ps1)'
